### PR TITLE
searches movie by title, friends by email,

### PR DESCRIPTION
**Pull request by ghost**
-made edits to routes in friendsService and moviesService to handle jget requests
-added a few users to user collection when testing searching by email, the users inserted had empty lists for groups and friends.

### CODE REVIEW

**Comment by ghost** [comment]
-left a few console.log() statements in there

**Comment by JohnStarich** [comment]
I believe you won't need the movie search routes and views any longer. Go ahead and remove those first.

**Comment by JohnStarich** [comment]
You're also welcome to copy what I did for movies and use it for users and groups too

**Comment by ghost** [comment]
closing this. going to move forward with what's on master.

**Pull request closed without merging**
